name: flags

services:
  db:
    build:
      context: Data-Harvester/DB
    volumes:
      - db-config:/data/configdb
      - db-data:/data/db
    secrets:
      - db-root-user
      - db-root-pass
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db-root-user
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db-root-pass
    ports:
      - "27017:27017"
    networks:
      - flags
  be:
    build:
      context: BE
    volumes:
      - cert-public:/etc/ssl/certs/flags
      - cert-private:/etc/ssl/private/flags
    depends_on:
      - db
    networks:
      - flags
    ports:
      - "444:444"
  fe:
    build:
      context: FE/app
    volumes:
      - cert-public:/etc/ssl/certs/flags
      - cert-private:/etc/ssl/private/flags
    depends_on:
      - be
    ports:
      - "443:444"
      - "80:80"
  data-harvester:
    build:
      context: Data-Harvester
    depends_on:
      - db
    networks:
      - flags
  cert-manager:
    build:
      context: Certificate-Manager
    volumes:
      - cert-public:/etc/ssl/certs/flags
      - cert-private:/etc/ssl/private/flags

volumes:
  db-config:
  db-data:
  cert-public:
  cert-private:

secrets:
  db-root-user:
    file: .secrets/db-root-user
  db-root-pass:
    file: .secrets/db-root-pass

networks:
  flags: