name: flags

services:
  db:
    build:
      context: Data-Harvester/DB
      secrets:
        - db-root-user
        - db-root-pass
        - db-data-harvester-user
        - db-data-harvester-pass
        - db-backend-user
        - db-backend-pass
    secrets:
      - db-root-user
      - db-root-pass
      - db-data-harvester-user
      - db-data-harvester-pass
      - db-backend-user
      - db-backend-pass
    volumes:
      - db-data:/data/db
      - cert-public:/etc/ssl/certs/flags
      - cert-private:/etc/ssl/private/flags
      - db-logs:/var/log/mongodb
      - db-dumps:/var/mongo/dumps
    ports:
      - "27017:27017"
    networks:
      - flags
  be:
    build:
      context: BE
    volumes:
      - cert-public:/etc/ssl/certs/flags
      - cert-private:/etc/ssl/private/flags
      - be-cache:/var/cache/nginx/flags
      - be-nginx-logs:/var/log/nginx
    depends_on:
      - db
    networks:
      - flags
    ports:
      - "444:444"
  fe:
    build:
      context: FE/app
    volumes:
      - cert-public:/etc/ssl/certs/flags
      - cert-private:/etc/ssl/private/flags
      - fe-nginx-logs:/var/log/nginx
    depends_on:
      - be
    ports:
      - "443:444"
      - "80:80"
  data-harvester:
    build:
      context: Data-Harvester
    depends_on:
      - db
    networks:
      - flags
    volumes:
      - data-harvest-logs:/opt/flags/logs
      - data-harvest-data:/opt/flags/data
      - cert-public:/etc/ssl/certs/flags
      - cert-private:/etc/ssl/private/flags
    post_start:
      - command: chown -R flags-data-harvester:flags-data-harvester 
                 /opt/flags/logs 
                 /opt/flags/data && 
                 chmod -R 700 /opt/flags/logs /opt/flags/data
        user: root
    command: ["--storage", "db"]
  cert-manager:
    build:
      context: Certificate-Manager
    volumes:
      - cert-public:/etc/ssl/certs/flags
      - cert-private:/etc/ssl/private/flags

volumes:
  db-data:
  db-logs:
  db-dumps:
  cert-public:
  cert-private:
  data-harvest-logs:
  data-harvest-data:
  be-cache:
  be-nginx-logs:
  fe-nginx-logs:

secrets:
  db-root-user:
    file: .secrets/db-root-user
  db-root-pass:
    file: .secrets/db-root-pass
  db-data-harvester-user:
    file: .secrets/db-data-harvester-user
  db-data-harvester-pass:
    file: .secrets/db-data-harvester-pass
  db-backend-user:
    file: .secrets/db-backend-user
  db-backend-pass:
    file: .secrets/db-backend-pass

networks:
  flags: